// src/utils/leaflet-fix.js

import L from 'leaflet'

// This module corrects the asset paths for Leaflet's default marker icons.
// When using a bundler like Vite or Webpack, the default paths generated by Leaflet
// can be incorrect, leading to missing marker images. This fix manually constructs
// the correct URLs to the marker images within node_modules and applies them.

// 1. Delete the internal URL resolver to prevent Leaflet from generating incorrect paths.
delete L.Icon.Default.prototype._getIconUrl

// 2. Manually set the correct paths for the default marker icons.
//    We use `import.meta.url` to create URLs relative to the current module,
//    ensuring they resolve correctly regardless of the application's structure.
L.Icon.Default.mergeOptions({
  iconRetinaUrl: new URL('../../node_modules/leaflet/dist/images/marker-icon-2x.png', import.meta.url)
    .href,
  iconUrl: new URL('../../node_modules/leaflet/dist/images/marker-icon.png', import.meta.url).href,
  shadowUrl: new URL('../../node_modules/leaflet/dist/images/marker-shadow.png', import.meta.url).href,
})
